In [44]:
import numpy as np
import pandas as pd

In [3]:
#1. Define two custom numpy arrays, say A and B. Generate two new numpy
# arrays by stacking A and B vertically and horizontally.

a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

c = np.vstack([a,b])
d = np.hstack([a,b])

print(c)
print(d)

[[1 2 3]
 [1 2 3]]
[1 2 3 1 2 3]


In [10]:
#2. Find common elements between A and B. [Hint : Intersection of two sets]

lst = []
for i in a:
    if (np.isin(i,b)):
        lst.append(i)
        
e = np.array(lst)

print(e)

[1 2 3]


In [41]:
#3. Extract all numbers from A which are within a specific range. eg
# between 5 and 10. [Hint: np.where() might be useful or boolean masks]

a = np.arange(1,20)

g = (a > 5)

newarr = np.array(a[g])

g = (newarr < 10)

newarr = np.array(newarr[g])

print(newarr)

[6 7 8 9]


In [42]:
# 4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5
# and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


# print(iris_2d)

iris_2d = iris_2d[(iris_2d[:,2] > 1.5)]

iris_2d = iris_2d[(iris_2d[:,0] < 5)]

print(iris_2d)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [98]:
# 5. From df filter the 'Manufacturer', 'Model' and 'Type' for every
# 20th row starting from 1st (row 0).

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

newdf = df[df.index % 20 == 0]

print(newdf)

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
20     Chrysler  LeBaron  Compact       14.5   15.8       17.1      23.0   
40        Honda  Prelude   Sporty       17.0   19.8       22.7      24.0   
60      Mercury   Cougar  Midsize       14.9   14.9       14.9      19.0   
80       Subaru   Loyale    Small       10.5   10.9       11.3      25.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0   
20         28.0  Driver & Passenger      Front  ...        6.0   183.0   
40         31.0  Driver & Passenger      Front  ...        4.0   175.0   
60         26.0                None       Rear  ...        5.0   199.0   
80         30.0                None        4WD  ...        5.0   175.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0    

In [101]:
# 6. Replace missing values in Min.Price and Max.Price columns with
# their respective mean.
import math

for index, row in df.iterrows():
#     print(row['Min.Price'])
    if (math.isnan(row['Min.Price']) or math.isnan(row['Max.Price'])):
        row['Min.Price'] = row['Price']
        
        df.at[i,'Min.Price'] = row['Price']
        df.at[i,'Max.Price'] = row['Price']

        
print(df)

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31

In [105]:
#7. How to get the rows of a dataframe with row sum > 100?

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))


newdf = df[df.sum(axis=1, numeric_only=True) > 100]

print(newdf)

     0   1   2   3
0   16  33  36  29
2   18  23  34  32
3   33  19  25  31
5   16  29  27  36
6   19  30  33  37
13  24  38  22  32
